#!/bin/bash

set -ex

OUTDIR="build/"$(basename ${1})
rm -rf $OUTDIR
mkdir -p $OUTDIR

#which arm-none-eabi-gcc
#which arm-none-eabi-gcc-ar
#which arm-none-eabi-ar
#echo $PATH
cmake -B $OUTDIR -DCMAKE_TOOLCHAIN_FILE=$1 ${@:3} --preset $2 .

#which arm-none-eabi-gcc
#which arm-none-eabi-gcc-ar
#which arm-none-eabi-ar
#ls -l /home/sru/repos/lean-ftl/xpacks/.bin/

cmake --build $OUTDIR --verbose --clean-first 
