#!/bin/bash

set -ex

PRESET=${1:-minSizeRel}

./buildit on/linux $PRESET

WCH=`which riscv-wch-elf-gcc || true`
if [[ ! -z "$WCH" ]]; then
    # if WCH toolchain seems to be present
    ./buildit on/ch32v307-wch-elf $PRESET
fi

EMBED=`which riscv-none-embed-gcc || true`
if [[ ! -z "$EMBED" ]]; then
    # if EMBED toolchain seems to be present
    ./buildit on/ch32v307-none-embed $PRESET
fi

ARM_NONE_EABI=`which arm-none-eabi-gcc || true`
if [[ ! -z "$ARM_NONE_EABI" ]]; then
    # if ARM_NONE_EABI toolchain seems to be present
    #generic builds, need user to implement accessors
    ./buildit on/cortex-m0 $PRESET
    ./buildit on/cortex-m3 $PRESET
    ./buildit on/cortex-m4 $PRESET
    ./buildit on/cortex-m7 $PRESET
    ./buildit on/cortex-m23 $PRESET
    ./buildit on/cortex-m33 $PRESET
    ./buildit on/cortex-m35p $PRESET
    ./buildit on/cortex-m52 $PRESET
    ./buildit on/cortex-m55 $PRESET
    ./buildit on/cortex-m85 $PRESET
    #targeted builds for few specific MCUs
    ./buildit on/stm32u5 $PRESET
    ./buildit on/stm32l5 $PRESET
fi

RISCV_NONE_ELF=`which riscv-none-elf-gcc || true`
if [[ ! -z "$RISCV_NONE_ELF" ]]; then
    # if RISCV_NONE_ELF toolchain seems to be present
    #generic builds, need user to implement accessors
    ./buildit on/rv32imc $PRESET
    #targeted builds for few specific MCUs
    ./buildit on/ch32v307 $PRESET
fi

OUT=dist/$PRESET/liblean-ftl
rm -rf $OUT
mkdir -p $OUT
cp LICENSE $OUT
cp -R liblean-ftl/include $OUT
cp -R liblean-ftl/source $OUT
mv build $OUT
git status
git diff package.json
sha256sum package.json
git describe --tags --always --dirty --match "v*" > $OUT/version.txt
cd dist/$PRESET
OUT_FILE=liblean-ftl-$PRESET.tar.gz
tar czf $OUT_FILE liblean-ftl
sha256sum $OUT_FILE > $OUT_FILE.sha256sum
cd ../..
rm -rf $OUT
mv dist/$PRESET/* dist
rm -rf dist/$PRESET