#!/bin/bash

set -ex

PRESET=${1:-minSizeRel}


./testit on/linux $PRESET
./clean
./buildit on/cortex-m0 $PRESET
./buildit on/cortex-m3 $PRESET
./buildit on/cortex-m4 $PRESET
./buildit on/cortex-m7 $PRESET
./buildit on/cortex-m23 $PRESET
./buildit on/cortex-m33 $PRESET
./buildit on/cortex-m35p $PRESET
./buildit on/cortex-m52 $PRESET
./buildit on/cortex-m55 $PRESET
./buildit on/cortex-m85 $PRESET

OUT=dist/$PRESET/liblean-ftl
rm -rf $OUT
mkdir -p $OUT
cp LICENSE $OUT
cp -R liblean-ftl/include $OUT
cp -R liblean-ftl/source $OUT
mv build $OUT
git status
git diff package.json
sha256sum package.json
git describe --tags --always --dirty --match "v*" > $OUT/version.txt
cd dist/$PRESET
7z a liblean-ftl-$PRESET.7z liblean-ftl
sha512sum liblean-ftl-$PRESET.7z > liblean-ftl-$PRESET.7z.sha512sum
cd ../..
rm -rf $OUT
mv dist/$PRESET/* dist
rm -rf dist/$PRESET