#!/bin/bash

set -ex

OUTDIR="build/build-"$1
./buildit $*
cd $OUTDIR
#make test #sometime that hangs
./lean-ftl-test

gcc ../../examples/hello/hello.c -o hello -I../../liblean-ftl/include \
    -Lliblean-ftl -llean-ftl 
./hello