#!/bin/bash

set -ex

OUTDIR="build/"$(basename ${1})

./buildit $*

cd $OUTDIR

#examples are always built for linux regardless of the selected target

INCLUDES="-I../../liblean-ftl/include -I../../liblean-ftl-test/include" 
LIBS="-Lliblean-ftl -llean-ftl -Lliblean-ftl-test -llean-ftl-test" 
DEFINES="-DLFTL_PAGE_SIZE=8*1024 -DLFTL_WU_SIZE=16 -DLINUX=1"

gcc -Og ../../examples/hello/main.c -o hello $INCLUDES $LIBS 

gcc -O0 -g3 -ggdb -E ../../examples/single_area/main.c $DEFINES -I../../examples/single_area $INCLUDES > single_area_main.c.i
gcc -O0 -g3 -ggdb ../../examples/single_area/main.c ../../target/linux/linux.c -o single_area $DEFINES $INCLUDES $LIBS

./lean-ftl-test-fw

./hello

./single_area