name: on-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install xpm
        run: |
          npm install --global xpm@latest
          xpm install @xpack-dev-tools/arm-none-eabi-gcc@14.2.1-1.1.1
          xpm install --no-save  @xpack-dev-tools/riscv-none-elf-gcc@14.2.0-3.1
          xpm install @xpack-dev-tools/cmake@3.30.7-1.1
      - name: Satisfy project dependencies
        run: xpm install
      - name: build
        shell: bash
        run: |
          git status
          PATH=`pwd`/xpacks/.bin:$PATH
          ./build-release 1 lean-ftl-${{github.ref_name}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: lean-ftl-${{github.ref_name}}.tar.gz