name: on-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install 7z
        shell: bash
        run: |
          sudo apt update
          sudo apt -yq install p7zip-full
      - name: Install xpm
        run: |
          npm install --global xpm@latest
          xpm install @xpack-dev-tools/arm-none-eabi-gcc@latest
          xpm install @xpack-dev-tools/cmake@latest
      - name: Satisfy project dependencies
        run: xpm install
      - name: build
        shell: bash
        run: |
          PATH=`pwd`/xpacks/.bin:$PATH
          ./build_release debug
          ./build_release minSizeRel
          tar czf lean-ftl-${{github.ref_name}}.tar.gz dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: lean-ftl-${{github.ref_name}}.7z