name: Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
    #workaround for package.json: it gets modified during "xpm install" somehow, so we backup it and restore it before launching the build
    - name: Install xpm
      run: |
        sha256sum package.json
        cp package.json package.bu
        npm install --no-save --global xpm@latest
        xpm install @xpack-dev-tools/arm-none-eabi-gcc@14.2.1-1.1.1
        xpm install --no-save  @xpack-dev-tools/riscv-none-elf-gcc@14.2.0-3.1
        xpm install @xpack-dev-tools/cmake@3.30.7-1.1
        sha256sum package.json
    - name: Satisfy project dependencies
      run: xpm install --no-save 
    - name: build
      shell: bash
      run: |
        echo before restoration
        sha256sum package.json
        ls -l
        rm package.json
        mv package.bu package.json
        echo after restoration
        sha256sum package.json
        ls -l
        git status
        PATH=`pwd`/xpacks/.bin:$PATH
        ./build-release 1 lean-ftl-${{github.ref_name}}
        #./buildit on/cortex-m0 debug
        echo after build
        sha256sum package.json
        ls -l
    - name: Archive temp artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-preview
        path: dist
        compression-level: 0 # no compression

  